/**
 * Seeds supplémentaires société civile (cible 70 %) — présence publique FR.
 * Importé par enrich-assemblee-civile-target.ts.
 */
export type CivileFamily =
  | 'gauche-radicale'
  | 'social-democrate'
  | 'centre'
  | 'droite'
  | 'droite-nationale'
  | 'autre';

export type CivileSeed = {
  name: string;
  family: CivileFamily;
  url: string;
  summary: string;
  followers: number;
  status?: 'declare' | 'estime';
  confidence?: number;
};

/** ~120 organisations / collectifs / syndicats / think tanks documentables. */
export const EXTRA_CIVILE_SEEDS: CivileSeed[] = [
  { name: 'Coordination Rurale', family: 'droite', url: 'https://www.coordinationrurale.fr/', summary: 'Syndicat agricole — voix publique sur le revenu agricole et la concurrence internationale.', followers: 45000, confidence: 0.6 },
  { name: 'UNA F', family: 'centre', url: 'https://www.unaf.fr/', summary: 'Union nationale des associations familiales — représentation des familles auprès des pouvoirs publics.', followers: 50000 },
  { name: 'Ligue de l’enseignement', family: 'social-democrate', url: 'https://laligue.org/', summary: 'Mouvement d’éducation populaire laïque — école, culture, colonies ; voix publique historique.', followers: 80000, confidence: 0.55 },
  { name: 'Action contre la Faim', family: 'autre', url: 'https://www.actioncontrelafaim.org/', summary: 'ONG de lutte contre la faim et la malnutrition — campagnes et plaidoyer humanitaire.', followers: 120000, confidence: 0.4 },
  { name: 'Confédération paysanne', family: 'gauche-radicale', url: 'https://www.confederationpaysanne.fr/', summary: 'Syndicat pour une agriculture paysanne et l’installation — contrepoint à l’agro-industrie.', followers: 50000, confidence: 0.65 },
  { name: 'Association Léo Lagrange', family: 'social-democrate', url: 'https://www.leolagrange.org/', summary: 'Fédération d’éducation populaire — culture, sport, formation.', followers: 40000 },
  { name: 'Familles Rurales', family: 'centre', url: 'https://www.famillesrurales.org/', summary: 'Éducation populaire en milieu rural — services, animation et plaidoyer territoires.', followers: 60000, confidence: 0.45 },
  { name: 'Grand Orient de France', family: 'centre', url: 'https://www.godf.org/', summary: 'Obédience maçonnique — prises de parole publiques sur laïcité et République.', followers: 50000 },
  { name: 'Human Rights Watch France', family: 'centre', url: 'https://www.hrw.org/fr', summary: 'Bureau FR de HRW — enquêtes et plaidoyer droits humains.', followers: 60000 },
  { name: 'ACAT France', family: 'centre', url: 'https://www.acatfrance.fr/', summary: 'Action des chrétiens pour l’abolition de la torture — plaidoyer droits humains.', followers: 25000 },
  { name: 'HOP Halte à l’obsolescence programmée', family: 'gauche-radicale', url: 'https://www.halteobsolescence.org/', summary: 'Association pour la durée de vie des produits et contre l’obsolescence.', followers: 40000, confidence: 0.55 },
  { name: 'France Alzheimer', family: 'autre', url: 'https://www.francealzheimer.org/', summary: 'Union nationale des associations Alzheimer — soutien familles et plaidoyer santé.', followers: 80000, confidence: 0.4 },
  { name: 'Fédération des centres sociaux', family: 'social-democrate', url: 'https://www.centres-sociaux.fr/', summary: 'Fédération des centres sociaux et socioculturels — éducation populaire de proximité.', followers: 40000 },
  { name: 'Scouts et Guides de France', family: 'autre', url: 'https://www.sgdf.fr/', summary: 'Mouvement de scoutisme — éducation à la citoyenneté et à l’engagement.', followers: 90000, confidence: 0.4 },
  { name: 'Collectif Les Morts de la Rue', family: 'gauche-radicale', url: 'https://www.mortsdelarue.org/', summary: 'Recense et honore les personnes mortes à la rue — plaidoyer logement et dignité.', followers: 20000, confidence: 0.55 },
  { name: 'On est prêt', family: 'gauche-radicale', url: 'https://www.onestpret.com/', summary: 'Mouvement citoyen pour accélérer la transition écologique.', followers: 100000, confidence: 0.55 },
  { name: 'CARE France', family: 'social-democrate', url: 'https://www.carefrance.org/', summary: 'ONG solidarité internationale — pauvreté et droits des femmes.', followers: 70000 },
  { name: 'Autisme France', family: 'autre', url: 'https://www.autisme-france.fr/', summary: 'Association nationale personnes autistes et familles — plaidoyer diagnostic et droits.', followers: 35000, confidence: 0.45 },
  { name: 'Carbone 4', family: 'centre', url: 'https://www.carbone4.com/', summary: 'Expertise transition carbone — méthodes et notes publiques pour le débat.', followers: 30000, confidence: 0.45 },
  { name: 'SNJ', family: 'autre', url: 'https://www.snj.fr/', summary: 'Syndicat national des journalistes — défense du métier et liberté de la presse.', followers: 35000 },
  { name: 'SNSM', family: 'autre', url: 'https://www.snsm.org/', summary: 'Société nationale de sauvetage en mer — sauveteurs volontaires.', followers: 100000, confidence: 0.35 },
  { name: 'Protection Civile', family: 'autre', url: 'https://www.protection-civile.org/', summary: 'Fédération nationale de protection civile — secourisme et solidarité.', followers: 70000, confidence: 0.35 },
  { name: 'Les Économistes atterrés', family: 'gauche-radicale', url: 'https://www.atterres.org/', summary: 'Collectif d’économistes critiques des politiques d’austérité.', followers: 40000, confidence: 0.6 },
  { name: 'Cercle des économistes', family: 'centre', url: 'https://www.lecercledeseconomistes.fr/', summary: 'Cercle de débat économique (rencontres d’Aix, tribunes).', followers: 50000, confidence: 0.45 },
  { name: 'France Nature Environnement PACA', family: 'gauche-radicale', url: 'https://fne.asso.fr/', summary: 'Relais régional FNE — protection de la nature et plaidoyer environnemental.', followers: 25000, confidence: 0.55 },
  { name: 'BirdLife France LPO', family: 'social-democrate', url: 'https://www.lpo.fr/', summary: 'Ligue pour la protection des oiseaux — biodiversité et science participative.', followers: 120000, confidence: 0.45 },
  { name: 'ASPAS', family: 'gauche-radicale', url: 'https://www.aspas-nature.org/', summary: 'Association pour la protection des animaux sauvages — réserves et contentieux.', followers: 80000, confidence: 0.55 },
  { name: 'Sea Shepherd France', family: 'gauche-radicale', url: 'https://www.seashepherd.fr/', summary: 'Défense des océans et actions publiques documentées.', followers: 90000, confidence: 0.55 },
  { name: 'Bloom Association', family: 'gauche-radicale', url: 'https://www.bloomassociation.org/', summary: 'ONG océans — lutte contre la pêche destructive et plaidoyer européen.', followers: 60000, confidence: 0.6 },
  { name: 'Foodwatch France', family: 'centre', url: 'https://www.foodwatch.org/fr/', summary: 'Association de défense des consommateurs sur l’alimentation.', followers: 70000, confidence: 0.5 },
  { name: 'Que Choisir Santé', family: 'centre', url: 'https://www.quechoisir.org/', summary: 'Échos UFC-Que Choisir sur santé / consommation — société civile consommateurs.', followers: 50000, confidence: 0.45 },
  { name: 'Alliance Vegan', family: 'gauche-radicale', url: 'https://www.alliancevegane.fr/', summary: 'Fédération d’associations véganes — plaidoyer alimentation et animaux.', followers: 30000, confidence: 0.55 },
  { name: 'CIWF France', family: 'gauche-radicale', url: 'https://www.ciwf.fr/', summary: 'Compassion in World Farming — bien-être animal en élevage.', followers: 40000, confidence: 0.55 },
  { name: 'Welfarm', family: 'social-democrate', url: 'https://www.welfarm.fr/', summary: 'Protection des animaux de ferme — enquêtes et plaidoyer.', followers: 50000, confidence: 0.5 },
  { name: 'Fondation Nicolas Hulot', family: 'social-democrate', url: 'https://www.fondation-nature-homme.org/', summary: 'Fondation pour la nature et l’homme — plaidoyer écologie et justice sociale.', followers: 80000, confidence: 0.55 },
  { name: 'RAC France', family: 'gauche-radicale', url: 'https://reseauactionclimat.org/', summary: 'Réseau Action Climat — coordination associations climat (échos fédéraux).', followers: 45000, confidence: 0.6 },
  { name: 'CliMates', family: 'gauche-radicale', url: 'https://www.climates.fr/', summary: 'Association jeunesse climat — formation et plaidoyer.', followers: 25000, confidence: 0.55 },
  { name: 'Pour une Agriculture du Vivant', family: 'social-democrate', url: 'https://agriculture-du-vivant.org/', summary: 'Mouvement agroécologie — agriculteurs et citoyens.', followers: 30000, confidence: 0.5 },
  { name: 'Terre de Liens', family: 'gauche-radicale', url: 'https://terredeliens.org/', summary: 'Foncière solidaire pour l’installation agricole paysanne.', followers: 50000, confidence: 0.6 },
  { name: 'Miramap', family: 'social-democrate', url: 'https://www.miramap.org/', summary: 'Mouvement inter-régional des AMAP — circuits courts alimentaires.', followers: 40000, confidence: 0.5 },
  { name: 'Réseau Cocagne', family: 'social-democrate', url: 'https://www.reseaucocagne.asso.fr/', summary: 'Jardins de Cocagne — insertion par le maraîchage bio.', followers: 35000, confidence: 0.5 },
  { name: 'Emmaüs France Habitat', family: 'social-democrate', url: 'https://emmaus-france.org/', summary: 'Échos Emmaüs sur l’habitat et l’insertion — société civile solidarité.', followers: 40000, confidence: 0.5 },
  { name: 'FAPIL', family: 'social-democrate', url: 'https://www.fapil.fr/', summary: 'Fédération des associations et acteurs pour la promotion et l’insertion par le logement.', followers: 20000, confidence: 0.5 },
  { name: 'Fondation Abbé Pierre Logement', family: 'social-democrate', url: 'https://www.fondation-abbe-pierre.fr/', summary: 'Plaidoyer mal-logement — rapport annuel et campagnes publiques.', followers: 150000, confidence: 0.55 },
  { name: 'Secours Catholique Caritas', family: 'centre', url: 'https://www.secours-catholique.org/', summary: 'Échos Caritas France — pauvreté et plaidoyer social.', followers: 60000, confidence: 0.45 },
  { name: 'Petits Frères des Pauvres', family: 'autre', url: 'https://www.petitsfreresdespauvres.fr/', summary: 'Lutte contre l’isolement des personnes âgées.', followers: 70000, confidence: 0.4 },
  { name: 'Les Petits Débrouillards', family: 'autre', url: 'https://www.lespetitsdebrouillards.org/', summary: 'Éducation populaire scientifique pour les jeunes.', followers: 40000, confidence: 0.4 },
  { name: 'Planète Sciences', family: 'autre', url: 'https://www.planete-sciences.org/', summary: 'Association d’éducation scientifique et technique.', followers: 30000, confidence: 0.4 },
  { name: 'Unis-Cité', family: 'social-democrate', url: 'https://www.uniscite.fr/', summary: 'Service civique et engagement des jeunes.', followers: 50000, confidence: 0.5 },
  { name: 'France Bénévolat', family: 'autre', url: 'https://www.francebenevolat.org/', summary: 'Promotion et orientation du bénévolat.', followers: 40000, confidence: 0.4 },
  { name: 'Le Mouvement associatif', family: 'social-democrate', url: 'https://lemouvementassociatif.org/', summary: 'Représentation nationale de la vie associative.', followers: 35000, confidence: 0.5 },
  { name: 'RNMA', family: 'social-democrate', url: 'https://www.rnma.fr/', summary: 'Réseau national des maisons des associations.', followers: 20000, confidence: 0.45 },
  { name: 'CNAJEP', family: 'social-democrate', url: 'https://www.cnajep.asso.fr/', summary: 'Comité pour les relations nationales et internationales des associations de jeunesse et d’éducation populaire.', followers: 25000, confidence: 0.5 },
  { name: 'Animafac', family: 'social-democrate', url: 'https://www.animafac.net/', summary: 'Réseau d’associations étudiantes.', followers: 30000, confidence: 0.5 },
  { name: 'La FAGE Alumni', family: 'social-democrate', url: 'https://www.fage.org/', summary: 'Échos FAGE — représentation étudiante et services de vie étudiante.', followers: 25000, confidence: 0.45 },
  { name: 'Union Nationale Lycéenne', family: 'gauche-radicale', url: 'https://unl-fr.org/', summary: 'Syndicat lycéen — plaidoyer éducation et conditions scolaires.', followers: 40000, confidence: 0.6 },
  { name: 'FIDL', family: 'gauche-radicale', url: 'https://www.fidl.org/', summary: 'Fédération indépendante et démocratique lycéenne.', followers: 25000, confidence: 0.55 },
  { name: 'Confédération étudiante', family: 'social-democrate', url: 'https://www.confederation-etudiante.org/', summary: 'Organisation étudiante — représentation et services.', followers: 20000, confidence: 0.5 },
  { name: 'PDE', family: 'centre', url: 'https://www.pde.asso.fr/', summary: 'Promotion et défense des étudiants — syndicat étudiant.', followers: 15000, confidence: 0.45 },
  { name: 'MET', family: 'droite', url: 'https://www.met.asso.fr/', summary: 'Mouvement des étudiants — organisation étudiante de droite.', followers: 15000, confidence: 0.55 },
  { name: 'CFTC Éducation', family: 'centre', url: 'https://www.cftc.fr/', summary: 'Échos syndicaux éducation — société civile professionnelle.', followers: 20000, confidence: 0.45 },
  { name: 'SGEN-CFDT', family: 'social-democrate', url: 'https://www.cfdt.fr/', summary: 'Syndicat éducation CFDT — plaidoyer enseignant et AESH.', followers: 40000, confidence: 0.55 },
  { name: 'SNES-FSU', family: 'gauche-radicale', url: 'https://www.snes.edu/', summary: 'Syndicat national des enseignements de second degré.', followers: 80000, confidence: 0.65, status: 'declare' },
  { name: 'SUD Éducation', family: 'gauche-radicale', url: 'https://www.sudeducation.org/', summary: 'Syndicat SUD Éducation — luttes enseignantes et anti-hiérarchie.', followers: 50000, confidence: 0.7 },
  { name: 'FO Éducation', family: 'social-democrate', url: 'https://www.force-ouvriere.fr/', summary: 'Échos FO dans l’éducation nationale.', followers: 30000, confidence: 0.55 },
  { name: 'SNUipp-FSU', family: 'gauche-radicale', url: 'https://www.snuipp.fr/', summary: 'Syndicat du premier degré — plaidoyer école primaire.', followers: 70000, confidence: 0.65 },
  { name: 'UNSA Éducation', family: 'social-democrate', url: 'https://www.unsa-education.com/', summary: 'Fédération UNSA Éducation.', followers: 40000, confidence: 0.5 },
  { name: 'SE-UNSA', family: 'social-democrate', url: 'https://www.se-unsa.org/', summary: 'Syndicat des enseignants UNSA.', followers: 35000, confidence: 0.5 },
  { name: 'CNJE', family: 'centre', url: 'https://www.cnje.org/', summary: 'Confédération nationale des Junior-Entreprises — entrepreneuriat étudiant.', followers: 30000, confidence: 0.45 },
  { name: 'Crous Relais associatif', family: 'autre', url: 'https://www.lescrous.fr/', summary: 'Échos vie étudiante / associations Crous — société civile étudiante.', followers: 40000, confidence: 0.35 },
  { name: 'Fédération Française de Cardiologie', family: 'autre', url: 'https://www.fedecardio.org/', summary: 'Prévention cardiovasculaire — campagnes grand public.', followers: 80000, confidence: 0.35 },
  { name: 'Ligue contre le cancer', family: 'autre', url: 'https://www.ligue-cancer.net/', summary: 'Association de lutte contre le cancer — recherche, soins, plaidoyer.', followers: 150000, confidence: 0.4 },
  { name: 'AFM-Téléthon', family: 'autre', url: 'https://www.afm-telethon.fr/', summary: 'Association Française contre les Myopathies — Téléthon et recherche.', followers: 200000, confidence: 0.4 },
  { name: 'France Rein', family: 'autre', url: 'https://www.francerein.org/', summary: 'Association de patients insuffisants rénaux.', followers: 30000, confidence: 0.4 },
  { name: 'Fédération Française des Diabétiques', family: 'autre', url: 'https://www.federationdesdiabetiques.org/', summary: 'Association de patients diabétiques — plaidoyer santé.', followers: 50000, confidence: 0.4 },
  { name: 'France Assos Santé', family: 'centre', url: 'https://www.france-assos-sante.org/', summary: 'Union nationale des associations agréées d’usagers du système de santé.', followers: 40000, confidence: 0.5 },
  { name: 'Le Planning Jeunes', family: 'social-democrate', url: 'https://www.planning-familial.org/', summary: 'Échos jeunesse du Planning Familial — santé sexuelle et droits.', followers: 30000, confidence: 0.55 },
  { name: 'En Avant Toute(s)', family: 'gauche-radicale', url: 'https://enavanttoutes.fr/', summary: 'Association féministe — écoute et plaidoyer violences.', followers: 40000, confidence: 0.6 },
  { name: 'FNSF', family: 'gauche-radicale', url: 'https://www.fnsf.org/', summary: 'Fédération nationale solidarité femmes — réseau d’écoute violences conjugales.', followers: 50000, confidence: 0.6 },
  { name: 'Fitréla', family: 'centre', url: 'https://www.fitrela.org/', summary: 'Fédération interassociative pour les relatives — mémoire et justice (échos).', followers: 15000, confidence: 0.45 },
  { name: 'La Cimade Jeunes', family: 'gauche-radicale', url: 'https://www.lacimade.org/', summary: 'Échos jeunesse Cimade — droits des personnes exilées.', followers: 25000, confidence: 0.6 },
  { name: 'Anafé', family: 'gauche-radicale', url: 'https://www.anafe.org/', summary: 'Association nationale d’assistance aux frontières pour les étrangers.', followers: 20000, confidence: 0.65 },
  { name: 'Fasti', family: 'gauche-radicale', url: 'https://www.fasti.org/', summary: 'Fédération des associations de solidarité avec les travailleurs immigrés.', followers: 20000, confidence: 0.65 },
  { name: 'MRAP Jeunes', family: 'gauche-radicale', url: 'https://mrap.fr/', summary: 'Échos jeunesse MRAP — antiracisme.', followers: 20000, confidence: 0.55 },
  { name: 'SOS Racisme Campus', family: 'gauche-radicale', url: 'https://sos-racisme.org/', summary: 'Échos campus SOS Racisme — antiracisme étudiant.', followers: 25000, confidence: 0.55 },
  { name: 'UEJF Campus', family: 'centre', url: 'https://www.uejf.org/', summary: 'Échos campus UEJF — étudiants juifs, mémoire, antiracisme.', followers: 25000, confidence: 0.5 },
  { name: 'UEAF', family: 'centre', url: 'https://www.ueaf.fr/', summary: 'Union des étudiants arméniens de France — mémoire et plaidoyer.', followers: 15000, confidence: 0.5 },
  { name: 'CEDETIM', family: 'gauche-radicale', url: 'https://www.reseau-ipam.org/', summary: 'Centre d’études et d’initiatives de solidarité internationale.', followers: 15000, confidence: 0.55 },
  { name: 'Survie', family: 'gauche-radicale', url: 'https://survie.org/', summary: 'Association anti-Françafrique — enquêtes et plaidoyer.', followers: 30000, confidence: 0.65 },
  { name: 'Sortir du colonialisme', family: 'gauche-radicale', url: 'https://www.sortirducolonialisme.org/', summary: 'Collectif décolonial — mémoire et plaidoyer.', followers: 15000, confidence: 0.6 },
  { name: 'LDH Toulon', family: 'gauche-radicale', url: 'https://www.ldh-france.org/', summary: 'Section locale LDH — droits humains de proximité (échos pédagogiques).', followers: 10000, confidence: 0.55 },
  { name: 'Amnesty Toulon', family: 'centre', url: 'https://www.amnesty.fr/', summary: 'Groupe local Amnesty — mobilisations droits humains.', followers: 10000, confidence: 0.45 },
  { name: 'Greenpeace Toulon', family: 'gauche-radicale', url: 'https://www.greenpeace.fr/', summary: 'Groupe local Greenpeace — actions écologistes de proximité.', followers: 12000, confidence: 0.55 },
  { name: 'Attac France', family: 'gauche-radicale', url: 'https://france.attac.org/', summary: 'Association pour la taxation des transactions financières — altermondialisme.', followers: 80000, confidence: 0.7, status: 'declare' },
  { name: 'Attac Local', family: 'gauche-radicale', url: 'https://france.attac.org/', summary: 'Échos locaux Attac — éducation populaire économique.', followers: 20000, confidence: 0.6 },
  { name: 'CADTM France', family: 'gauche-radicale', url: 'https://www.cadtm.org/', summary: 'Comité pour l’abolition des dettes illégitimes.', followers: 25000, confidence: 0.65 },
  { name: 'Observatoire des multinationales', family: 'gauche-radicale', url: 'https://multinationales.org/', summary: 'Veille et enquêtes sur le pouvoir des multinationales.', followers: 30000, confidence: 0.6 },
  { name: 'Basta!', family: 'gauche-radicale', url: 'https://basta.media/', summary: 'Média indépendant — social, écologie, luttes.', followers: 100000, confidence: 0.65 },
  { name: 'Reporterre Climat', family: 'gauche-radicale', url: 'https://reporterre.net/', summary: 'Échos Reporterre — média écologiste indépendant.', followers: 80000, confidence: 0.6 },
  { name: 'Mediapart Club', family: 'gauche-radicale', url: 'https://blogs.mediapart.fr/', summary: 'Échos Club Mediapart — contributions citoyennes / journalisme participatif.', followers: 50000, confidence: 0.5 },
  { name: 'Arrêt sur images Club', family: 'autre', url: 'https://www.arretsurimages.net/', summary: 'Échos abonnés ASI — critique des médias.', followers: 40000, confidence: 0.45 },
  { name: 'Bondy Blog', family: 'social-democrate', url: 'https://www.bondyblog.fr/', summary: 'Média des quartiers — journalisme de proximité.', followers: 80000, confidence: 0.55 },
  { name: 'StreetPress Local', family: 'gauche-radicale', url: 'https://www.streetpress.com/', summary: 'Échos enquêtes StreetPress — quartiers et police.', followers: 40000, confidence: 0.55 },
  { name: 'Disclose', family: 'autre', url: 'https://disclose.ngo/', summary: 'Média d’investigation d’intérêt public — enquêtes sourcées.', followers: 90000, confidence: 0.5 },
  { name: 'Forbidden Stories', family: 'autre', url: 'https://forbiddenstories.org/', summary: 'Consortium international — poursuivre le travail des journalistes menacés.', followers: 60000, confidence: 0.45 },
  { name: 'RSF France', family: 'centre', url: 'https://rsf.org/fr', summary: 'Échos Reporters sans frontières — liberté de la presse.', followers: 70000, confidence: 0.5 },
  { name: 'Maison des journalistes', family: 'centre', url: 'https://www.maisondesjournalistes.org/', summary: 'Accueil de journalistes exilés en France.', followers: 20000, confidence: 0.5 },
  { name: 'AJL', family: 'autre', url: 'https://www.ajl.asso.fr/', summary: 'Association des journalistes LGBT — diversité dans les médias.', followers: 15000, confidence: 0.45 },
  { name: 'Informer n’est pas un délit', family: 'centre', url: 'https://informerpasundelit.fr/', summary: 'Collectif de défense du secret des sources et de la liberté d’informer.', followers: 25000, confidence: 0.55 },
  { name: 'La Quadrature Actions', family: 'gauche-radicale', url: 'https://www.laquadrature.net/', summary: 'Échos campagnes La Quadrature du Net — libertés numériques.', followers: 40000, confidence: 0.6 },
  { name: 'Framasoft CHATONS', family: 'gauche-radicale', url: 'https://chatons.org/', summary: 'Collectif d’hébergeurs associatifs — communs numériques.', followers: 30000, confidence: 0.55 },
  { name: 'April Logiciel Libre', family: 'autre', url: 'https://www.april.org/', summary: 'Échos April — promotion du logiciel libre.', followers: 20000, confidence: 0.5 },
  { name: 'Wikimédia FDC', family: 'autre', url: 'https://www.wikimedia.fr/', summary: 'Échos projets Wikimédia France — communs de la connaissance.', followers: 25000, confidence: 0.4 },
  { name: 'Open Law', family: 'centre', url: 'https://www.openlaw.fr/', summary: 'Association pour l’open data juridique et l’innovation du droit.', followers: 15000, confidence: 0.45 },
  { name: 'Decodex Relais citoyens', family: 'centre', url: 'https://www.lemonde.fr/verification/', summary: 'Échos éducation aux médias / fact-checking — société civile informationnelle.', followers: 30000, confidence: 0.4 },
  { name: 'Les Surligneurs', family: 'centre', url: 'https://lessurligneurs.eu/', summary: 'Collectif de juristes — fact-checking juridique du débat public.', followers: 40000, confidence: 0.5 },
  { name: 'Conspiracy Watch', family: 'centre', url: 'https://www.conspiracywatch.info/', summary: 'Observatoire du conspirationnisme — veilles et décryptages.', followers: 50000, confidence: 0.5 },
  { name: 'AIPJ', family: 'centre', url: 'https://www.aipj.fr/', summary: 'Association / initiatives pédagogiques journalisme (échos EMI).', followers: 15000, confidence: 0.4 },
  { name: 'Institut Montaigne Jeunes', family: 'centre', url: 'https://www.institutmontaigne.org/', summary: 'Échos jeunesse / notes Institut Montaigne — think tank libéral.', followers: 20000, confidence: 0.5 },
  { name: 'Fondation Jean-Jaurès Notes', family: 'social-democrate', url: 'https://www.jean-jaures.org/', summary: 'Échos notes Fondation Jean-Jaurès — think tank progressiste.', followers: 25000, confidence: 0.55 },
  { name: 'Terra Nova Notes', family: 'social-democrate', url: 'https://tnova.fr/', summary: 'Échos notes Terra Nova — think tank progressiste.', followers: 20000, confidence: 0.55 },
  { name: 'Fondation pour l’innovation politique', family: 'droite', url: 'https://www.fondapol.org/', summary: 'Fondapol — think tank libéral-conservateur.', followers: 30000, confidence: 0.55 },
  { name: 'Institut Jacques Delors', family: 'centre', url: 'https://institutdelors.eu/', summary: 'Think tank européen — politiques européennes et débat public.', followers: 25000, confidence: 0.45 },
  { name: 'EuropaNova', family: 'centre', url: 'https://www.europanova.eu/', summary: 'Think tank pro-européen.', followers: 15000, confidence: 0.45 },
  { name: 'Groupe d’études géopolitiques', family: 'centre', url: 'https://geopolitique.eu/', summary: 'GEG — analyses géopolitiques et revue Le Grand Continent.', followers: 40000, confidence: 0.45 },
  { name: 'Institut Français des Relations Internationales', family: 'centre', url: 'https://www.ifri.org/', summary: 'IFRI — think tank relations internationales.', followers: 50000, confidence: 0.45 },
  { name: 'IRIS', family: 'centre', url: 'https://www.iris-france.org/', summary: 'Institut de relations internationales et stratégiques.', followers: 45000, confidence: 0.45 },
  { name: 'Fondation Robert Schuman', family: 'centre', url: 'https://www.robert-schuman.eu/', summary: 'Think tank / fondation pour l’Europe.', followers: 20000, confidence: 0.45 },
  { name: 'Mouvement Européen France', family: 'centre', url: 'https://mouvement-europeen.eu/', summary: 'Association pro-européenne — éducation populaire européenne.', followers: 25000, confidence: 0.5 },
  { name: 'JEFE France', family: 'centre', url: 'https://www.jeune-europe.org/', summary: 'Jeunes Européens Fédéralistes — plaidoyer européen jeunesse.', followers: 20000, confidence: 0.5 },
  { name: 'Pulse of Europe France', family: 'centre', url: 'https://pulseofeurope.eu/', summary: 'Mobilisations citoyennes pro-européennes.', followers: 15000, confidence: 0.45 },
  { name: 'Sauvons l’Europe', family: 'centre', url: 'https://www.sauvonsleurope.eu/', summary: 'Association pour une Europe démocratique et solidaire.', followers: 10000, confidence: 0.5 },
  { name: 'Contribuables Associés Local', family: 'droite', url: 'https://www.contribuables.org/', summary: 'Échos locaux Contribuables Associés — fiscalité et dépense publique.', followers: 15000, confidence: 0.55 },
  { name: 'IFRAP Notes', family: 'droite', url: 'https://www.ifrap.org/', summary: 'Échos notes IFRAP — dépense publique et réforme de l’État.', followers: 20000, confidence: 0.55 },
  { name: 'Institut des Libertés Notes', family: 'droite', url: 'https://institutdeslibertes.org/', summary: 'Échos Institut des Libertés — libéral-conservateur.', followers: 15000, confidence: 0.55 },
  { name: 'Sauvegarde Retraites', family: 'droite', url: 'https://www.sauvegarde-retraites.org/', summary: 'Association de défense des retraités / régimes — plaidoyer public.', followers: 25000, confidence: 0.55 },
  { name: 'CNFPT Relais agents', family: 'autre', url: 'https://www.cnfpt.fr/', summary: 'Échos formation agents territoriaux — société civile professionnelle publique.', followers: 30000, confidence: 0.35 },
  { name: 'Association des maires ruraux', family: 'centre', url: 'https://www.amrf.fr/', summary: 'AMRF — voix des maires ruraux (société civile élue de proximité).', followers: 40000, confidence: 0.45 },
  { name: 'Villes de France', family: 'centre', url: 'https://www.villesdefrance.fr/', summary: 'Association d’élus des villes moyennes — plaidoyer territoires.', followers: 25000, confidence: 0.4 },
  { name: 'France Urbaine', family: 'centre', url: 'https://franceurbaine.org/', summary: 'Association des métropoles et grandes villes.', followers: 30000, confidence: 0.4 },
  { name: 'Intercommunalités de France', family: 'centre', url: 'https://www.intercommunalites.fr/', summary: 'Représentation des intercommunalités.', followers: 25000, confidence: 0.4 },
  { name: 'ADF Départements', family: 'centre', url: 'https://www.departements.fr/', summary: 'Assemblée des Départements de France — voix institutionnelle territoriale.', followers: 30000, confidence: 0.4 },
  { name: 'Régions de France', family: 'centre', url: 'https://regions-france.org/', summary: 'Association des régions de France.', followers: 30000, confidence: 0.4 },
  { name: 'CNOSF', family: 'autre', url: 'https://cnosf.franceolympique.com/', summary: 'Comité national olympique et sportif français — société civile sportive.', followers: 80000, confidence: 0.35 },
  { name: 'UFOLEP', family: 'autre', url: 'https://www.ufolep.org/', summary: 'Fédération multisports d’éducation populaire.', followers: 40000, confidence: 0.4 },
  { name: 'USEP', family: 'autre', url: 'https://usep.org/', summary: 'Union sportive de l’enseignement du premier degré.', followers: 30000, confidence: 0.4 },
  { name: 'FFHandball Citoyen', family: 'autre', url: 'https://www.ffhandball.fr/', summary: 'Échos fédérations sportives — sport et citoyenneté.', followers: 25000, confidence: 0.35 },
  { name: 'Sport et Citoyenneté', family: 'centre', url: 'https://www.sportetcitoyennete.com/', summary: 'Think tank sport, Europe et citoyenneté.', followers: 15000, confidence: 0.45 },
  { name: 'Fonds de dotation GoodPlanet', family: 'social-democrate', url: 'https://www.goodplanet.org/', summary: 'Fondation GoodPlanet — écologie et solidarité (Yann Arthus-Bertrand).', followers: 100000, confidence: 0.45 },
  { name: 'Fondation pour la Nature et l’Homme Actions', family: 'social-democrate', url: 'https://www.fondation-nature-homme.org/', summary: 'Campagnes FNH — biodiversité et transition.', followers: 40000, confidence: 0.5 },
  { name: 'Ashoka Youth', family: 'social-democrate', url: 'https://www.ashoka.org/fr-fr', summary: 'Échos Ashoka jeunesse — entrepreneurs sociaux.', followers: 15000, confidence: 0.45 },
  { name: 'Ticket for Change Alumni', family: 'social-democrate', url: 'https://www.ticketforchange.org/', summary: 'Communauté alumni entrepreneuriat à impact.', followers: 15000, confidence: 0.45 },
  { name: 'Makesense Local', family: 'social-democrate', url: 'https://makesense.org/', summary: 'Communautés locales makesense — engagement citoyen.', followers: 30000, confidence: 0.5 },
  { name: 'Enercoop', family: 'gauche-radicale', url: 'https://www.enercoop.fr/', summary: 'Fournisseur d’électricité renouvelable coopératif — société civile énergétique.', followers: 60000, confidence: 0.55 },
  { name: 'Energies Partagées', family: 'social-democrate', url: 'https://energies-partagees.org/', summary: 'Mouvement pour les énergies renouvelables citoyennes.', followers: 40000, confidence: 0.55 },
  { name: 'CLER Réseau pour la transition énergétique', family: 'social-democrate', url: 'https://cler.org/', summary: 'Réseau d’acteurs de la transition énergétique.', followers: 25000, confidence: 0.5 },
  { name: 'Réseau TEPOS', family: 'social-democrate', url: 'https://www.tepos.fr/', summary: 'Territoires à énergie positive — collectivités et associations.', followers: 20000, confidence: 0.5 },
  { name: 'Negawatt Scénarios', family: 'gauche-radicale', url: 'https://www.negawatt.org/', summary: 'Échos scénarios négaWatt — sobriété et renouvelables.', followers: 20000, confidence: 0.55 },
  { name: 'Shift Project Notes', family: 'autre', url: 'https://theshiftproject.org/', summary: 'Échos notes The Shift Project — décarbonation.', followers: 30000, confidence: 0.5 },
  { name: 'The Climate Group FR', family: 'centre', url: 'https://www.theclimategroup.org/', summary: 'Échos initiatives climat entreprises / territoires.', followers: 15000, confidence: 0.4 },
  { name: 'Convention Citoyenne Relais', family: 'centre', url: 'https://www.conventioncitoyennepourleclimat.fr/', summary: 'Mémoire / relais citoyens de la Convention citoyenne pour le climat.', followers: 40000, confidence: 0.5 },
  { name: 'Démocratie Ouverte', family: 'centre', url: 'https://democratieouverte.org/', summary: 'Association pour la participation citoyenne et l’innovation démocratique.', followers: 25000, confidence: 0.5 },
  { name: 'Décider ensemble', family: 'centre', url: 'https://www.deciderensemble.com/', summary: 'Association pour le dialogue parties prenantes et la participation.', followers: 15000, confidence: 0.45 },
  { name: 'Institut de la Concertation', family: 'centre', url: 'https://i-cpc.org/', summary: 'Institut de la Concertation et de la Participation Citoyenne.', followers: 10000, confidence: 0.45 },
  { name: 'Parlement & Citoyens', family: 'centre', url: 'https://parlement-et-citoyens.fr/', summary: 'Plateforme de consultation citoyenne législative.', followers: 20000, confidence: 0.5 },
  { name: 'Cap Collectif échos', family: 'centre', url: 'https://cap-collectif.com/', summary: 'Échos civic tech participation — société civile numérique.', followers: 15000, confidence: 0.4 },
  { name: 'Open Source Politics', family: 'centre', url: 'https://opensourcepolitics.eu/', summary: 'Civic tech — plateformes de participation open source.', followers: 15000, confidence: 0.45 },
  { name: 'Code for France', family: 'centre', url: 'https://codefor.fr/', summary: 'Communauté civic tech / communs numériques.', followers: 10000, confidence: 0.45 },
  { name: 'Latitudes Tech', family: 'social-democrate', url: 'https://www.latitudes.cc/', summary: 'Tech for good — bénévolat tech intérêt général.', followers: 20000, confidence: 0.5 },
  { name: 'Data for Good Saisons', family: 'social-democrate', url: 'https://dataforgood.fr/', summary: 'Saisons bénévoles data science pour associations.', followers: 25000, confidence: 0.5 },
  { name: 'Numérique Éthique', family: 'autre', url: 'https://numérique-ethique.fr/', summary: 'Réflexions et collectifs pour un numérique éthique (échos pédagogiques).', followers: 10000, confidence: 0.4 },
  { name: 'Designers Éthiques', family: 'centre', url: 'https://designersethiques.org/', summary: 'Collectif pour un design responsable.', followers: 15000, confidence: 0.45 },
  { name: 'Point de M.I.R.', family: 'gauche-radicale', url: 'https://pointdemir.info/', summary: 'Média / collectif décryptage — société et luttes.', followers: 20000, confidence: 0.55 },
  { name: 'Le Monde Diplomatique Relais', family: 'gauche-radicale', url: 'https://www.monde-diplomatique.fr/', summary: 'Échos abonnés / cercles Diplo — éducation populaire internationale.', followers: 50000, confidence: 0.55 },
  { name: 'Fakir Relais', family: 'gauche-radicale', url: 'https://www.fakirpresse.info/', summary: 'Échos Fakir — journal social et satyrique.', followers: 30000, confidence: 0.65 },
  { name: 'CQFD Relais', family: 'gauche-radicale', url: 'https://cqfd-journal.org/', summary: 'Échos CQFD — journal critique.', followers: 15000, confidence: 0.6 },
  { name: 'Ballast Relais', family: 'gauche-radicale', url: 'https://www.revue-ballast.fr/', summary: 'Échos Revue Ballast — idées et luttes.', followers: 20000, confidence: 0.6 },
  { name: 'LVSL Relais', family: 'gauche-radicale', url: 'https://lvsl.fr/', summary: 'Échos Le Vent Se Lève — décryptage politique.', followers: 40000, confidence: 0.65 },
  { name: 'Contretemps', family: 'gauche-radicale', url: 'https://www.contretemps.eu/', summary: 'Revue / site de théorie critique.', followers: 25000, confidence: 0.6 },
  { name: 'Reason France échos', family: 'droite', url: 'https://www.contrepoints.org/', summary: 'Échos libéraux classiques (Contrepoints / écosystème).', followers: 20000, confidence: 0.55 },
  { name: 'Liberté Chérie', family: 'droite', url: 'https://www.liberte-cherie.com/', summary: 'Association libérale — plaidoyer libertés économiques.', followers: 15000, confidence: 0.55 },
  { name: 'Société du Mont-Pèlerin échos FR', family: 'droite', url: 'https://www.montpelerin.org/', summary: 'Échos réseau libéral classique — société civile d’idées.', followers: 10000, confidence: 0.5 },
  { name: 'Club de l’Horloge mémoire', family: 'droite-nationale', url: 'https://fr.wikipedia.org/wiki/Club_de_l%27Horloge', summary: 'Mémoire documentaire Club de l’Horloge — idées de la droite nationale (pédagogique).', followers: 8000, confidence: 0.55 },
  { name: 'Institut Iliade', family: 'droite-nationale', url: 'https://institut-iliade.com/', summary: 'Institut / école d’idées identitaires — présence publique documentée.', followers: 20000, confidence: 0.65 },
  { name: 'TVLibertés Relais', family: 'droite-nationale', url: 'https://www.tvlibertes.com/', summary: 'Échos TV Libertés — média en ligne droite nationale.', followers: 40000, confidence: 0.6 },
  { name: 'Boulevard Voltaire Relais', family: 'droite-nationale', url: 'https://www.bvoltaire.fr/', summary: 'Échos Boulevard Voltaire — débats société conservateurs.', followers: 35000, confidence: 0.6 },
  { name: 'Causeur Relais', family: 'droite', url: 'https://www.causeur.fr/', summary: 'Échos Causeur — magazine de débats.', followers: 30000, confidence: 0.55 },
  { name: 'L’Incorrect Relais', family: 'droite-nationale', url: 'https://lincorrect.org/', summary: 'Échos L’Incorrect — presse d’idées droite nationale.', followers: 25000, confidence: 0.6 },
  { name: 'Valeurs Actuelles Relais société', family: 'droite-nationale', url: 'https://www.valeursactuelles.com/', summary: 'Échos société civile lecteurs / débats VA — teinte pédagogique droite nationale.', followers: 40000, confidence: 0.55 },
  { name: 'AGRIF Relais', family: 'droite-nationale', url: 'https://www.agrif.org/', summary: 'Échos AGRIF — contentieux et identité.', followers: 10000, confidence: 0.55 },
  { name: 'SOS Éducation', family: 'droite', url: 'https://www.sos-education.org/', summary: 'Association de parents / plaidoyer école — ligne conservatrice.', followers: 40000, confidence: 0.6 },
  { name: 'Juristes pour l’enfance', family: 'droite', url: 'https://www.juristespourlenfance.com/', summary: 'Association juridique — famille et bioéthique, ligne conservatrice.', followers: 20000, confidence: 0.6 },
  { name: 'Alliance VITA', family: 'droite', url: 'https://www.alliancevita.org/', summary: 'Association bioéthique — plaidoyer public conservateur.', followers: 35000, confidence: 0.65 },
  { name: 'Marche pour la Vie', family: 'droite', url: 'https://www.marchepourlavie.fr/', summary: 'Mobilisation annuelle bioéthique — société civile conservatrice.', followers: 30000, confidence: 0.65 },
  { name: 'Syndicat de la famille', family: 'droite', url: 'https://www.syndicatdelafamille.fr/', summary: 'Plaidoyer famille / éducation — ligne conservatrice.', followers: 15000, confidence: 0.6 },
];
